// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ANTest.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30000
#error This file was generated by a different version of protoc-gen-objc which is incompatible with your Protocol Buffer sources.
#endif

// @@protoc_insertion_point(imports)

CF_EXTERN_C_BEGIN

@class Request;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AntestRoot

@interface AntestRoot : GPBRootObject

// The base class provides:
//   + (GPBExtensionRegistry *)extensionRegistry;
// which is an GPBExtensionRegistry that includes all the extensions defined by
// this file and all files that it depends on.

@end

#pragma mark - Request

typedef GPB_ENUM(Request_FieldNumber) {
  Request_FieldNumber_Cmdid = 1,
  Request_FieldNumber_Timestamp = 2,
};

// 全局请求格式体
@interface Request : GPBMessage

@property(nonatomic, readwrite) int32_t cmdid;

@property(nonatomic, readwrite) int64_t timestamp;

@end

#pragma mark - ANFile

typedef GPB_ENUM(ANFile_FieldNumber) {
  ANFile_FieldNumber_Filename = 1,
  ANFile_FieldNumber_URL = 2,
  ANFile_FieldNumber_Content = 3,
  ANFile_FieldNumber_Mimetype = 4,
};

// 全局文件格式
@interface ANFile : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *filename;

@property(nonatomic, readwrite, copy, null_resettable) NSString *uRL;

@property(nonatomic, readwrite, copy, null_resettable) NSData *content;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mimetype;

@end

#pragma mark - testMessage

typedef GPB_ENUM(testMessage_FieldNumber) {
  testMessage_FieldNumber_Common = 1,
  testMessage_FieldNumber_Content = 2,
};

// 测试文本消息请求
@interface testMessage : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) Request *common;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

@end

#pragma mark - testMessageWithImage

typedef GPB_ENUM(testMessageWithImage_FieldNumber) {
  testMessageWithImage_FieldNumber_Common = 1,
  testMessageWithImage_FieldNumber_Content = 2,
  testMessageWithImage_FieldNumber_ImagesArray = 3,
};

// 测试文本带图片消息请求
@interface testMessageWithImage : GPBMessage

@property(nonatomic, readwrite) BOOL hasCommon;
@property(nonatomic, readwrite, strong, null_resettable) Request *common;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

// |imagesArray| contains |ANFile|
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray *imagesArray;
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

// @@protoc_insertion_point(global_scope)
